### ISSUE TITLE
Determine Name of Npm Package and Update Code Examples

### ISSUE THREAD

**Issue by dhurlburtusa** [XcooBee/xcoobee-js-sdk#3]
We need to determine the name of the NPM package we plan to publish so that the code examples can be updated. The code examples assumed the package name was going to be `@xcoobee/sdk-js`.

This should pretty much be a search and replace task.

Note: Code examples are in `UsageExamples.md` and the JSDocs in the code itself. May be some in README.md too.

**Comment by Bilal-S** [comment]
Agreed.
In my documentation set I have this as `xcoobee-js-sdk` to match the repo name. 
This is also how it is published in npm right now.
We could change this to `xcoobee-sdk` as an alternative. I am ok with either one.

**Comment by dhurlburtusa** [comment]
It looks like we already published an NPM package with the name `xcoobee-js-sdk`. If we change it to `xcoobee-sdk` and publish, then we'll have two NPM for the same project. Is that the intention? Do be plan to deprecate the `xcoobee-js-sdk` package in favor of `xcoobee-sdk`?

**Comment by Bilal-S** [comment]
Dan,
I depricated `xcoobee-js-sdk` and added `xcoobee-sdk`. I will slack you.
